fbi-cde/crime-data-frontend

.cfignore
LICENSE.md
README.md
circle.yml
manifest.yml
package.json
server.js

Adds a `manifest.yml` so that the app runs on cloud.gov. For now, I have used express as a very small web server when `NODE_ENV='prod'`.
To close #4

Run the application on Cloud.gov

---

src/components/BarChart.js
src/components/XAxis.js

label / tick wasn't quite centered between bar before; this should
(hopefully) make it so
used this as my guide:
https://github.com/d3/d3-axis/blob/master/src/axis.js#L21

tweak x axis

---

.codeclimate.yml
.eslintrc
README.md
data/usa-states.json
sass/components/_glossary.scss
sass/core/_base-reset.scss
src/components/App.js
src/components/Cartogram.js
test/components/Cartogram.test.js

add basic usa square cartogram

---

README.md
package.json
server.js

Add /api/* as a passthrough endpoint to secure API key

---

sass/components/_breadcrumbs.scss
sass/components/all.scss
sass/core/_base-typography.scss
src/components/Breadcrumbs.js
src/components/Explorer.js
src/components/Term.js
src/routes.js

Add content heading

---

sass/_variables.scss
sass/app.scss
sass/components/_footer.scss
sass/components/all.scss
sass/util/_space-misc.scss
sass/util/all.scss
src/components/App.js
src/components/Footer.js
src/components/Navigation.js

main things: sticky bottom bottom, title / link alignment in header
preview:

header / footer tweaks

---

package.json
server.js
src/util/api.js
src/util/filters.js
src/util/http.js
test/sum.test.js
test/util/api.test.js
test/util/filters.test.js
test/util/http.test.js

Add API utility

---

package.json
src/components/App.js
src/components/Census.js
src/components/Explorer.js
src/components/Glossary.js
src/components/Sandbox.js
src/components/Term.js
src/components/TimeChart.js
src/util/data.js

Add census block and content summary components

---

package.json
webpack.config.js

we'll want to tweak the browserlist config once we pin down

add autoprefixer

---

src/components/Explorer.js
src/components/Sandbox.js
src/components/TimeChart.js
src/util/data.js
test/components/TimeChart.test.js

support multiple series for line chart

---

sass/_variables.scss
sass/components/_layout.scss
sass/components/all.scss
src/components/App.js
src/components/Navigation.js
src/components/Sandbox.js
src/components/Sidebar.js

add "holy grail" layout (with flexbox!)

---

.cfignore
.gitignore
newrelic.js
package.json
server.js

Add new relic for production server monitoring

---

sass/_variables.scss
sass/components/_breadcrumbs.scss
src/components/Breadcrumbs.js
src/components/Census.js
src/components/DetailsCard.js
src/components/Explorer.js
src/components/Navigation.js
src/components/Sandbox.js
src/components/Sidebar.js
src/components/Term.js

a bunch of little things around alignment and paddings and colors (using latest mocks)
definitely still a long way off but baby steps :)
preview:

add / adjust some style stuffz

---

sass/_variables.scss
sass/components/_tables.scss
sass/components/all.scss
sass/core/_base-tables.scss
src/components/Sandbox.js
src/components/Table.js

add basic table component / stylez

---

sass/util/_colors.scss
sass/util/_line-height.scss
sass/util/all.scss
src/components/App.js
src/components/DownloadsAndDocs.js
src/components/Header.js

add to downloads & docs page, clean up header

---

src/components/Hint.js
src/components/TimeChart.js

i don't love how i implemented this, but perhaps it's a decent start.
the more we customize these charts, the more i think we should just use this react charting library that uber open-sourced (which has all of this stuff + more and seems thoughtful and well done: http://uber.github.io/react-vis/) 
preview:

timechart tooltips, take 1

---

server.js

An unauthenticated endpoint for monitoring services to access
Closes #86

Add /status endpoint

---

sass/_variables.scss
src/components/Census.js
src/util/data.js

i know this will change again, but this looks a bit more in line with latest (mobile) mock:

update census stylez

---

sass/_variables.scss
src/components/CrimeTypeFilter.js
src/components/DetailsCard.js
src/components/Explorer.js
src/components/Header.js
src/components/LocationFilter.js
src/components/Sidebar.js
src/components/StateSvg.js
src/components/TimePeriodFilter.js

cosmetic tweaks

---

src/components/Disclaimer.js

Copyediting

---

sass/components/_charts.scss
src/components/TimeChart.js
src/components/TimeChartDetails.js
src/util/data.js

wire up time chart hover details

---

sass/components/_forms.scss
sass/components/all.scss
sass/core/_color-forms.scss
sass/util/_cursor.scss
sass/util/all.scss
src/components/CrimeTypeFilter.js
src/components/FilterGroup.js

update look of sidebar crime filter section

---

server.js
src/actions/summaryActions.js
src/components/Explorer.js
src/components/Sidebar.js
src/components/TimeChartDetails.js
src/entry.js
src/util/api.js

Using `crime-data-api2.fr.cloud.gov` to get summary data for the nation and the place. Right now, this doesn't display rates, since we don't yet have the population, but uses actual counts. Also, just displays data for "murder" as of now, but we should merge this (if we can) before the standup and I can continue the work in a separate branch/PR
Part of #95

Use summary data from API

---

sass/util/_colors.scss
src/components/CrimeTypeFilter.js
src/components/FilterGroup.js
src/util/api.js

type of crime filter updates

---

sass/components/_tables.scss
src/components/Explorer.js
src/components/Histogram.js
src/components/IncidentDetailCard.js
src/components/IncidentDetailTable.js
src/util/data.js

Use data from the API but preloaded into the application to display the NIBRS data
Refs [18F/crime-data-api#252](/18F/crime-data-api/issues/252)

Add data for detail view cards

---

src/components/AboutTheData.js

Adds links to further reading section

About the data

---

package.json
robots.txt
server.js

add robots, remove basic auth

---

package.json
server.js

Reverting from #145 per the client's request

Add back auth

---

src/components/DownloadsAndDocs.js

Small link addition for the sake of our ATO reviewers. Small change so I'll merge myself when green

Add api docs link to <DownloadAndDocs />

---

src/components/Disclaimer.js
src/components/Header.js

header / disclaimer visual update

---

src/components/App.js
src/components/Footer.js
src/components/Header.js

Some design tweaks to Header and Footer

---

sass/components/_viz.scss
sass/components/all.scss
src/components/Home.js

add state outline on hover

---

server.js

We were using `crime-data-api2.*` to request the data, but that server has been taken offline. I changed it back to `crime-data-api`

Fix trend charts

---

src/components/Glossary.js
src/components/LocationSelect.js
src/components/Term.js
src/store.js
src/util/api.js

cc: https://github.com/18F/crime-data-explorer/issues/170

remove prod logging, fix misc lints

---

src/components/CrimeTypeFilter.js
src/components/Explorer.js
src/components/NotFound.js
src/util/data.js

Explorer component now checks that place and crime are whitelisted values; if not, the NotFound component is returned
this addresses https://github.com/18F/crime-data-api/issues/333#issuecomment-275682888

explorer url whitelist

---

data/terms.json

Adds SRS, Hierarchy Rule, updates homicide notes

Updates terms

---

sass/util/_border.scss
sass/util/_colors.scss
src/components/Explorer.js
src/components/TimeChart.js
src/components/TimeChartDetails.js

Reverts 18F/crime-data-explorer#180

Revert "trend chart visual refinement"

---

src/components/Footer.js
src/components/LocationFilter.js
src/components/TimePeriodFilter.js
src/routes.js

Well the screen capture is pretty weird since it doesn't show clicks. There are now errors if you try and enter a year that is less than 1960, a year that is greater than 2014, if the end year is greater than the beginning year and if the years are not at least ten years apart.

Show errors for time period filter

---

src/components/Explorer.js
src/components/TrendChart.js
src/components/TrendChartDetails.js
src/components/TrendContainer.js
test/components/TrendChart.test.js

encapsulates the trend title box into the TrendContainer; will do the same for the NibrsContainer next, which will make things like the data downloading functionality easier, as well as tidies up the Explorer component

trend container component tweaks

---

src/components/Donut.js

preview:
(hover behavior still needs to be refined)

add donut chart component

---

src/components/Home.js
src/util/data.js

Per discussions with @larrybafundo and @amberwreed, removing human trafficking from the home page and crime type filter

Remove human trafficking & cargo theft as crime types

---

sass/_variables.scss
sass/util/_border.scss
sass/util/_type.scss
src/components/NibrsTable.js

Demo:
@LarryBafundo I don't see an issue for this one, is there one I'm missing? If not, I think @brendansudol can probably just provide comments/merge anyway. Just didn't want to orphan a card

Add toggle to nibrs tables for displaying count numbers or percents

---

sass/components/_header.scss
sass/components/all.scss
sass/util/_responsive-type.scss
sass/util/all.scss
src/components/Header.js

mobile header

---

src/components/Explorer.js
src/components/NibrsContainer.js
src/components/TrendContainer.js
src/util/api.js
src/util/glossary.js
src/util/offenses.js

Using [`classification`](https://github.com/18F/crime-data-api/issues/329#issuecomment-278129623), I wired up all property crime and all violent crime. Also did some small refactoring on the crime ID mapping
Refs #138

Add all violent crime and all property crime

---

src/components/CrimeTypeFilter.js
src/components/Home.js
src/util/data.js

Also adds violent crime and property crime to the home page menus

Remove hate crime and leoka from menus

---

content/datasets.yml
src/components/Home.js

The content is added but the buttons don't yet do anything as we do not have a place for them to go.

Add other data set content to homepage

---

content/datasets.yml

Fixes #247 — I may copyedit this further in a final editing pass but let’s go ahead and ship the changes if that’s okay with you.

Changes copy

---

content/crimes/aggravated-assault.yml
content/crimes/homicide.yml
content/crimes/rape.yml
content/crimes/robbery.yml
content/crimes/violent-crime.yml

Fixes #183 — may need to markdownify our yml as I am adding links here.

Adds relationship info

---

content/crimes/violent-crime.yml

Ensure violent crime content is valid YAML

---

package.json

Add yaml linter for content/

---

img/loading.svg
src/components/Loading.js

cc: https://github.com/18F/crime-data-explorer/issues/273

better data loading module

---

content/datasets.yml
sass/util/_border.scss
src/components/DownloadsAndDocs.js

Use other data set YAML file for constructing view

---

content/datasets.yml
src/components/Home.js

Fixes homepage tile / downloads tile and refines API language

Homepage refinements

---

src/util/nibrs.js

Slightly alter location name in NIBRS

---

package.json
src/components/AboutTheData.js

Convert about the data caveats text from Markdown to HTML
Refs #272

Convert about the data content to html from markdown

---

src/components/AboutTheData.js
src/components/TimePeriodFilter.js

cc: https://github.com/18F/crime-data-explorer/issues/226

input --> select for time period filters

---

src/components/Home.js

Oughta follow my own style guide rule there, eh.

Adds full term on first mention

---

src/components/Footer.js

- remove privacy link
- add GH links

Updates footer

---

src/components/NibrsContainer.js

Repeat location for clarity

---

README.md
manifest-demo.yml

From the retro yesterday we talked about having a separate environment for user testing
Closes #327

Add a manifest file for user testing

---

src/components/Hint.js
src/components/Home.js
src/components/UsaMap.js

this will also help us as we build the about page (which also has a usa map)

move usamap into its own component, add tooltips

---

data/terms.json

I broke the app by merging a JSON file before linting it. This should fix it

Fix terms.json

---

content/datasets.yml
src/components/DownloadBulkNibrs.js
src/components/DownloadsAndDocs.js

Fixes #305 - adds placeholder text for #344

Dataset text

---

src/components/TimePeriodFilter.js

Remove time period text

---

src/components/Home.js

Limit other datasets on homepage to three

---

src/components/NibrsContainer.js

Fixed the issue raised here https://github.com/18F/crime-data-explorer/issues/334#issuecomment-281528060

Fix NIBRS container text

---

content/crimes/burglary.yml

Adds hotel rule

---

src/components/About.js
src/components/AboutPage.js
src/routes.js

not pixel perfect, but an initial place that we can iterate on

about page start

---

content/crimes/aggravated-assault.yml
content/crimes/arson.yml
content/crimes/burglary.yml
content/crimes/hate-crime.yml
content/crimes/homicide.yml
content/crimes/human-trafficking.yml
content/crimes/larceny-theft.yml
content/crimes/motor-vehicle-theft.yml
content/crimes/property-crime.yml
content/crimes/rape.yml
content/crimes/robbery.yml
content/crimes/violent-crime.yml
src/components/Home.js
src/components/LocationSelect.js

Homepage copy

---

src/components/TrendChart.js

Switch trend chart colors

---

src/components/UcrParticipationInformation.js

Update UCR participation text

---

src/components/Explorer.js
src/util/glossary.js
src/util/offenses.js

Also fixes an issue where arson would not render

Do not show NIBRS data for property crime or violent crime

---

content/crimes/hate-crime.yml
content/crimes/homicide.yml

Adds caveat about crime/location issues

---

src/components/Header.js
src/components/Home.js

cc: https://github.com/18F/crime-data-explorer/issues/212

add home link

---

src/components/About.js

Staging copy for Ryan — this page still needs some FE work to match the design.

Updating About copy

---

sass/util/_layout.scss
sass/util/all.scss
src/components/NibrsContainer.js

cc: https://github.com/18F/crime-data-explorer/issues/345

fix nibrs grid line-up

---

src/components/Header.js

cc: https://github.com/18F/crime-data-explorer/issues/375

update nav order

---

src/components/NibrsTable.js

cc: https://github.com/18F/crime-data-explorer/issues/294

fix nibrs table truncating

---

src/components/Home.js
src/components/Term.js

cc: https://github.com/18F/crime-data-explorer/issues/336

fix term spacing (just uses html space now)

---

src/components/NibrsCard.js
src/components/NibrsHistogram.js
src/components/NibrsHistogramDetails.js
src/util/nibrs.js

Expect a noun prop with <Histogram />

---

content/datasets.yml

Alter S3 URLs for compiled data downloads

---

src/components/Home.js

Use a single link for other data sets

---

src/components/DownloadDataBtn.js
src/components/TrendContainer.js
src/util/csv.js
test/util/csv.test.js

1. Renames downloaded file to be `${place}-${crime}-${timeFrom}–${timeTo}.csv`
2. Flattens nested JSON data structure for a more useful/complete CSV
Fixes #372

Fix SRS download

---

data/terms.json

Also deletes two terms we don't need

Minor spacing fixes

---

sass/util/_colors.scss
src/components/About.js
src/components/UsaMap.js
src/util/ucr.js

@brendansudol Do you think this closes out #313 from a dev perspective?
I think this also closes #203

Color About page map based on UCR program participation

---

src/components/UcrParticipationInformation.js

Fix spacing when place reports SRS and NIBRS

---

src/components/NibrsTable.js

Use "reported" instead of "total" in <NibrsTable />

---

src/components/About.js

I don’t have copy for that third box and am skeptical that the copy
(links) in the other 2 boxes is going to look ok.

About edits

---

content/datasets.yml

Longer term, I think we should have the years somewhere in the design, but this is okay with me for the MVP.

Adds years, copyediting

---

src/components/About.js

I’m worried one of my deletions will affect the design/layout. If so
maybe I can change it back and find some copy to make things easier.

made a few more changes and minor edits

---

src/components/TrendChartDetails.js

Adjust trend chart detail font sizes

---

src/components/DownloadBulkNibrs.js

cc: https://github.com/18F/crime-data-explorer/issues/433

no usa in bulk download dropdown

---

src/components/Explorer.js

cc: https://github.com/18F/crime-data-explorer/issues/394

remove breadcrumbs

---

src/actions/compositeActions.js
src/actions/filterActions.js
src/components/Explorer.js
src/components/Home.js
src/entry.js
src/util/ucr.js
test/util/ucr.test.js

cc: https://github.com/18F/crime-data-explorer/issues/392
@jeremiak - i think this is a good opportunity to do a more broader refactor of this update filters + url + get data flow
this first commit is the start, but let's pair tomorrow and flesh it out more tomorrow

refactor filter update + url change + data fetch

---

content/crimes/property-crime.yml
content/crimes/violent-crime.yml
data/terms.json

Makes `hierarchy rule` sentence case like `hotel rule`, adds links.
@jeremiak Is it possible in the future to include glossary links here? I can open an issue if so, otherwise, this is fine for now. We only mention it 2x.

Make rules consistent

---

src/components/TrendChart.js
src/components/TrendChartDetails.js
src/components/XAxis.js
src/components/YAxis.js
src/entry.js

this PR creates 4 equally spaced y axis gridlines for the trend chart, FINALLY!
preview:

better trend y axis

---

src/components/TrendContainer.js
src/components/TrendSourceText.js
src/components/UcrParticipationInformation.js

Change trend chart source depending on state's data source

---

index.html

Snippet from: https://github.com/18F/analytics-standards#javascript-code-snippet
In the process of getting the UA code from the analytics guild, which is the remaining step.

Add basic analytic tracking code

---

src/components/About.js

submitted a number of edits and changes. I was going to wait until the redesign was implemented, but decided to go ahead now so other folks can see the edits.

Edits to crime data section

---

sass/util/_border.scss
sass/util/_layout.scss
src/components/App.js
src/components/BetaBanner.js
src/components/Disclaimer.js

new beta banner!

---

src/components/NibrsCard.js

Screenshot of `/explorer/district-of-columbia/arson`:
Refs #434

Handle case where a <NibrsCard /> is given data with values of 0

---

src/components/Footer.js
src/components/Link.js

Add <Link /> component to handle internal and external links

---

src/components/Footer.js
src/routes.js

Scroll to top of page on any URL changes

---

src/components/NibrsTable.js

Use a sentence to show total counts in <NibrsTable />

---

src/components/UcrParticipationInformation.js

Fixes #529 
I don’t love this but it’s clearer than the current text, and less repetitive. We still need to refine this section visually, @AvivaOskow is working on that.

Make link descriptive

---

src/components/NibrsContainer.js
src/util/ucr.js

Dynamic sentence for NIBRS years

---

src/components/Explorer.js
src/components/NibrsContainer.js
src/components/Sidebar.js
src/components/TimePeriodFilter.js
src/components/TrendChart.js
src/components/TrendContainer.js
src/components/TrendSourceText.js
src/components/UcrParticipationInformation.js
src/reducers/filters.js
src/util/api.js
test/components/TrendChart.test.js
test/util/api.test.js
test/util/history.test.js

* renames `timeFrom` to `since` and `timeTo` to `until` to avoid camelCasing in url and is more consistent with url param naming across the web
* better checks for ensuring these time filter fields are integers

timeFrom -> since, timeTo -> until, better type checks

---

src/components/TrendChart.js

a few trend refinements

---

sass/util/_colors.scss
src/components/NibrsHistogram.js
src/components/NibrsHistogramDetails.js
src/util/nibrs.js

Add axis labels to histograms and default text

---

src/util/nibrs.js

Clean NIBRS relationship labels

---

src/components/DownloadDataBtn.js
src/components/DownloadsAndDocs.js
src/components/NibrsCard.js
src/components/NibrsContainer.js
src/components/TrendChart.js
test/components/TrendChart.test.js

Trigger many CSV downloads from data download button

---

src/components/NibrsContainer.js
src/components/NibrsHistogram.js
src/components/NibrsHistogramDetails.js

Use proper plural words in histogram details

---

src/components/NibrsDonut.js
src/components/NibrsHistogram.js
src/components/TrendChart.js
src/components/TrendChartDetails.js
src/components/XAxis.js
src/util/nibrs.js

* histograms always now go from 0-100
* donuts now always have male, female, unknown
* charts now have x-axis padding / cushion

viz refinements

---

public/robots.txt
src/html.js
src/util/sharing.js
test/reducers/filters.test.js

Very basic approach to getting started with adding content for Facebook and Twitter to use when links are shared on those platforms.
Refs #576

Share meta tags

---

sass/components/_progress.scss
src/components/DownloadDataBtn.js
src/components/NibrsCard.js
src/components/NibrsDonut.js
src/components/NibrsDonutDetails.js
src/components/NibrsHistogram.js
src/components/NibrsTable.js

fixes: https://github.com/18F/crime-data-explorer/issues/573, https://github.com/18F/crime-data-explorer/issues/569

fixe 573, 569

---

src/util/sharing.js

Runtime errors from the `<meta>` tag sharing PR

Fix runtime server error in sharing util

---

sass/util/_layout.scss
src/components/BetaBanner.js

Thoughts @brendansudol and @AvivaOskow? From [a comment in crime-data-api#377](https://github.com/18F/crime-data-api/issues/377#issuecomment-285706765)

Alter breakpoint for beta banner

---

CHANGELOG.md
CONTRIBUTING.md
package.json

@brendansudol Let's talk about this one. I want to start doing a release process at the end of each sprint with a changelog and attempt to follow semver as closely as possible. As such, we have to start somewhere so I just bumped the version to 1.0.0. I'm interested to know how you feel about this.

Add CHANGELOG and bump version to 1.0.0

---

CONTRIBUTING.md

Update CONTRIBUTING with Redux and React Router

---

src/components/UcrParticipationInformation.js
src/reducers/ucr.js
src/util/ucr.js
test/util/ucr.test.js

fixes: https://github.com/18F/crime-data-explorer/issues/591 (formerly https://github.com/18F/crime-data-explorer/issues/318)
preview:

fix national participation n/a

---

sass/util/_border.scss
src/components/Explorer.js

make btn round and friendly

---

sass/util/_height.scss
src/components/TrendChart.js
src/components/TrendChartDetails.js

this addresses: https://github.com/18F/crime-data-explorer/issues/548, https://github.com/18F/crime-data-explorer/issues/588

trend tweaks

---

src/components/DownloadBulkNibrs.js
src/components/DownloadsAndDocs.js

fixes: https://github.com/18F/crime-data-explorer/issues/374

download & docs hierarchy

---

sass/util/_space-addon.scss
src/components/Explorer.js
src/components/Footer.js
src/components/Header.js

fixes: https://github.com/18F/crime-data-explorer/issues/623
fixes: https://github.com/18F/crime-data-explorer/issues/601

small fixes

---

src/components/DownloadsAndDocs.js

Update API docs link

---

src/util/api.js
test/util/api.test.js

Use state postal abbreviation in API calls

---

src/components/Glossary.js

Clear error in between terms and toggling

---

content/datasets.yml

Update police employee data link

---

content/locations.yml
src/components/UcrParticipationInformation.js
src/util/content.js

Added a national UCR link (to the FBI) and renamed the relevant
content YML file so that it is named locations instead of states,
since there is a national key now.
To fix #534

Add national UCR link, states.yml -> locations.yml

---

src/components/TrendChartDetails.js

Use different copy for national in trend chart

---

src/util/api.js
test/util/api.test.js

Use some of the re-organized endpoints so that we can remove them from the API.
Refs #620 #639

Use new API endpoints

---

src/components/App.js
src/entry.js

add clear localstorage button

---

sass/_variables.scss
sass/util/_space-addon.scss
src/components/BetaBanner.js
src/components/Explorer.js
src/components/Footer.js
src/components/Header.js

cc: https://github.com/18F/crime-data-api/issues/465

unify header, body, footer alignment

---

CHANGELOG.md
package.json

Update the version to account for adding HTTP basic authentication.

Update version and changelog to 1.3.0

---

src/components/TrendChart.js

cc: https://github.com/18F/crime-data-explorer/issues/34#event-1043557942

add circles for each data point in trend chart

---

sass/components/_list.scss
sass/util/_colors.scss

fixes: https://github.com/18F/crime-data-explorer/issues/35

tweak red rule for lists

---

.eslintrc
sass/components/_viz.scss
src/components/AgencyChart.js

* basic, responsive grouped bar chart component

agency bar chart start

---

.eslintrc
sass/util/_aspect-ratio.scss
src/components/App.js

turn on welcome modal

---

CHANGELOG.md
package.json

@brendansudol Can you take a look at this and see if I missed anything? I will go ahead and merge once I hear back from you so I can tag the merge commit.
Here is the [/compare](https://github.com/18F/crime-data-frontend/compare/v1.3.0...master) for this release if you want to use that.

Update CHANGELOG and README for v2.0.0

---

src/components/TrendChart.js

Closes https://github.com/18F/crime-data-frontend/issues/692

new axis label location

---

src/components/AgencyChart.js
src/components/AgencyChartContainer.js
src/components/AgencyChartDetails.js
src/components/App.js

* adds hover interaction, chart details, title

agency bar chart component iteration

---

data/terms.json

Closes 18F/crime-data-explorer#53

Add rural, suburban, and urban definitions to glossary terms

---

sass/_variables.scss
sass/components/_tables.scss
sass/util/_line-height.scss
src/components/AgencyTable.js

preview:
example usage:
```
<AgencyTable
data={[['apples', 123], ['oranges', 456], ['bananas', 789]]}
title="Title"
/>
```

start agency table

---

src/components/BetaModal.js
src/components/Feedback.js
src/components/FocusTrap.js
src/components/OnEscape.js
test/components/OnEscape.test.js

Properly handle Shift + Tab for feedback and beta modal

---

circle.yml
manifests/base.yml
manifests/demo.yml
manifests/master.yml
manifests/staging.yml

Manifest inheritance wasn't working. Used [these docs](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests) to troubleshoot

Fix deployment problems because of manifests

---

sass/_variables.scss
sass/util/_colors.scss
sass/util/_flex.scss
sass/util/_fonts.scss
sass/util/_width.scss
sass/util/all.scss
src/components/Feedback.js
src/util/github.js

Closes https://github.com/18F/crime-data-explorer/issues/55

Style feedback component

---

src/components/DownloadDataBtn.js
src/components/NibrsCard.js
src/components/TrendChart.js
src/components/TrendContainer.js
src/util/content.js

Generate a README for trend chart and NIBRS card downloads

---

src/components/UcrParticipationInformation.js

Change participation API endpoint for the participation CSV download
Closes #737

Use new participation endpoint for participation CSV download

---

src/reducers/filters.js
test/reducers/filters.test.js

Closes https://github.com/18F/crime-data-explorer/issues/76

violent crime as default

---

src/components/NibrsContainer.js

Closes https://github.com/18F/crime-data-explorer/issues/12

no year range in nibrs title

---

src/components/Home.js
src/reducers/filters.js
test/reducers/filters.test.js

Closes https://github.com/18F/crime-data-explorer/issues/75

clickable home map

---

content/crimes/aggravated-assault.yml
content/crimes/arson.yml
content/crimes/burglary.yml
content/crimes/homicide.yml
content/crimes/larceny-theft.yml
content/crimes/motor-vehicle-theft.yml
content/crimes/property-crime.yml
content/crimes/rape.yml
content/crimes/robbery.yml
content/crimes/violent-crime.yml
src/components/About.js
src/components/TrendSourceText.js
src/components/UcrParticipationInformation.js

Closes #685 18F/crime-data-explorer#14 18F/crime-data-explorer#24

Implement estimated content

---

src/components/Footer.js

User submitted feedback regarding a broken footer link
Closes https://github.com/18F/crime-data-explorer/issues/78

Fix "Explorer" footer link

---

content/datasets.yml

Change title of assaults on law enforcement officers dataset

---

src/components/Home.js

Closes https://github.com/18F/crime-data-explorer/issues/111

Fix API docs link on homepage

---

CHANGELOG.md
package.json

Please ignore the version bump here:
https://github.com/18F/crime-data-frontend/commit/60dc30376282833a13c22b765c2d7384bf9c842a

Bump version to v2.3.0

---

data/terms.json

Closes https://github.com/18F/crime-data-frontend/issues/600

Add "participation" to glossary terms

---

sass/util/_space-addon.scss
src/components/ExplorerHeader.js
src/components/LocationFilter.js
src/components/PlaceThumbnail.js
src/components/UcrParticipationInformation.js
src/util/api.js

move place thumbnail from sidebar

---

src/components/NibrsContainer.js
src/components/UcrParticipationInformation.js

Change explorer copy related to estimated data

---

src/components/About.js

Closes https://github.com/18F/crime-data-explorer/issues/138

Change "LEOKA" label in available datasets on About page

---

data/terms.json

adding estimated data to glossary

---

public/swagger/swagger.json

Point swagger to use /api-proxy instead of /api

---

src/components/Explorer.js
src/components/LocationFilter.js
src/components/SidebarContainer.js

Use `agencySearch=true` as a URL parameter to show the agency search box. Will not show by default

Hide agency search feature flag

---

sass/_variables.scss
src/components/NibrsTable.js
src/components/UcrParticipationContainer.js
src/util/nibrs.js

* hero content
* nibrs table design

agency page touchups

---

src/components/AboutTheData.js

Closes https://github.com/18F/crime-data-explorer/issues/93

Include offense type in About the Data heading

---

src/components/AgencyChart.js
src/components/AgencyChartContainer.js

To properly name the download files from the agency chart, I moved the
download button into the container component.
Closes https://github.com/18F/crime-data-explorer/issues/49

Move download button to AgencyChartContainer

---

src/components/TrendSourceText.js

https://github.com/18F/crime-data-explorer/issues/44#issuecomment-303800939

Capitalize "Estimated" in trend chart source text

---

CHANGELOG.md
package.json

@brendansudol Can you take a look and see if I missed anything?

bump version to 2.5.0

---

src/components/Glossary.js

closes https://github.com/18F/crime-data-frontend/issues/784

fixes map glossary overlap

---

src/components/AgencyChartContainer.js
src/util/api.js
test/util/api.test.js

wire up real data for agency bar chart

---

src/components/UcrParticipationContainer.js

Closes https://github.com/18F/crime-data-explorer/issues/160
Opened https://github.com/18F/crime-data-api/issues/526 as a result but this PR will fix things for now.

Participation CSV link is case sensitive

---

src/components/AgencyChartDetails.js
src/components/NibrsTable.js
src/components/PlaceThumbnail.js
src/components/UcrParticipationContainer.js
src/util/nibrs.js

* marker on map and label below map
* content tweaks

small stuff re: agency page

---

src/components/SparklineContainer.js
src/util/api.js
src/util/ori.js
test/util/ori.test.js

Closes https://github.com/18F/crime-data-frontend/issues/806

Handle Nebraska ORIs

---

src/components/Home.js
src/components/SidebarContainer.js

nav bug fixes

---

src/components/PlaceThumbnail.js

Make agency map dot a pin instead of a circle

---

src/components/AgencyChart.js

Display x axis in front of agency bar charts

---

src/components/AgencySearchResults.js
src/components/ExplorerAgencyIntroduction.js
src/components/ExplorerHeaderContainer.js
src/components/ExplorerIntroduction.js
src/components/UcrResourcesList.js

Change agency text to reflect the agency type and include agencies that do not have a primary county in the search results.
Also, include state and national UCR resources for agencies.
Refs #842

Change agency text

---

content/terms.json

https://github.com/18F/crime-data-explorer/issues/173

adding reported and cleared to the glossary

---

src/components/About.js

This addresses https://github.com/18F/crime-data-explorer/issues/149

emphasizing-data-updates

---

src/components/AgencySearchResults.js

Change agency search results county label for a11y

---

src/components/AgencySearch.js
src/util/ori.js

Remove agency type and fully clear agency search

---

content/terms.json
src/components/About.js

cleared  and crimes rate edits, also tweaks to the about page.

edits to the glossary

---

src/components/Explorer.js

this fixes bug where clicking "Explorer" in navbar didn't update / bring you to United States violent crime page

fix explorer link in nav bug

---

src/util/api.js
src/util/offenses.js

Use `violent` or `property` to request aggregate date for agencies

Map crime for violent and property for agencies

---

.scss-lint.yml
sass/_variables.scss
sass/components/_btn.scss
sass/components/_forms.scss
src/components/AgencySearch.js

refine agency search box

---

src/components/NibrsStackedBar.js

refs: https://github.com/18F/crime-data-frontend/issues/874
preview:

alpha ordering for stacked bar

---

sass/util/_flex.scss
src/components/Sparkline.js
src/components/SparklineContainer.js

Begin to make Sparklines responsive to smaller displays

---

sass/util/_space-addon.scss
src/components/Footer.js
test/components/All.test.js

Deployed to https://crime-data-explorer-jk-footer.fr.cloud.gov/
Refs https://github.com/18F/crime-data-explorer/issues/117

Footer is two columns on small displays

---

public/swagger/index.html
src/components/AgencySearch.js
src/components/NibrsHistogram.js
src/components/NibrsStackedBar.js
src/util/nibrs.js

* updated footer for api page
* remove 'incidents' label for stacked bar and histogram charts
* smaller text in agency search box

design tweaks per pairing w/ Aviva

---

src/components/AgencySearchResults.js

[📟 Preview: https://crime-data-explorer-jk-filter-federal-agencies.fr.cloud.gov](https://crime-data-explorer-jk-filter-federal-agencies.fr.cloud.gov)
Also show "No results" if there are no matches.
Refs https://github.com/18F/crime-data-frontend/issues/907

Filter out federal agencies from search results

---

src/components/AgencyChartContainer.js

Refs https://github.com/18F/crime-data-explorer/issues/187

Add data source info to agency chart

---

src/components/NibrsHistogram.js
src/components/NibrsStackedBar.js

refs: https://github.com/18F/crime-data-frontend/issues/912
preview:

remove dashed lines

---

src/components/AboutTheData.js
src/components/UcrResourcesList.js

refs: https://github.com/18F/crime-data-explorer/issues/184

fix broken explorer for dc

---

src/components/DownloadBulkNibrs.js

Use new NIBRS bulk download URLs with state abbreviation instead of ID

---

src/components/PlaceThumbnail.js
src/containers/ExplorerHeaderContainer.js

refs: https://github.com/18F/crime-data-frontend/issues/876

remove pin, tweak place label

---

public/swagger/index.html
src/components/Footer.js
src/components/NotFound.js

Increase footer icon size by 30%

---

src/components/AgencySearch.js

Also close the agency search with the escape key

Close agency search results when user clicks out of area

---

src/components/NibrsStackedBar.js
src/components/NibrsStackedBarDetails.js

closes: https://github.com/18F/crime-data-frontend/issues/930

remove bold, simplify stacked bar

---

content/datasets.yml
src/components/DownloadsAndDocs.js

Refs https://github.com/18F/crime-data-explorer/issues/194

Update estimated dataset description

---

src/components/ExplorerIntroNational.js
src/components/ExplorerIntroState.js

Add glossary term for crime type in intro text for nation and states

---

src/components/ExplorerIntroAgency.js

Show county text in agency intro only if type is city or university/college

---

src/components/AgencySearchResults.js

Make sure there is either of the months reported fields present before testing them
Refs #913

Inactivate search results for agencies with no data

---

public/data/ucr-program-participation.json
src/components/About.js
src/components/DownloadDataBtn.js
src/components/Footer.js
src/components/Header.js
test/util/ucr.test.js

Updated content and moved the participation map near the top of the About page

Update About and Footer components with new content

---

src/components/Glossary.js

Closes https://github.com/18F/crime-data-explorer/issues/197

Change glossary placeholder to "Crime rate"

---

src/components/NibrsTableWithBars.js

fixes: https://github.com/18F/crime-data-frontend/issues/985
preview:

fix text overflow

---

src/components/About.js

Include agencies participation download on About page

---

src/components/TrendChart.js

move trend labels to the left

---

src/containers/NibrsContainer.js

fixes: https://github.com/18F/crime-data-frontend/issues/996
preview:

fix nibrs card widths for tablets

---

src/components/DownloadBulkNibrs.js
src/components/DownloadsAndDocs.js

Refs https://github.com/18F/crime-data-explorer/issues/163 #867

Update download & docs page

---

package.json
src/components/About.js
src/components/DownloadsAndDocs.js
src/components/Explorer.js
src/components/Home.js
src/components/NotFound.js
src/html.js
src/server.js

uses: https://github.com/nfl/react-helmet
preview:

add dynamic page titles

---

src/html.js

fixes: https://github.com/18F/crime-data-frontend/issues/973

prevent page zoom

---

src/containers/ExplorerHeaderContainer.js

fixes: https://github.com/18F/crime-data-frontend/issues/992
preview:

show place thumbnail on tablet

---

sass/components/_layout.scss

should fix https://github.com/18F/crime-data-frontend/issues/799
(tested via browserstack)

fix layout bug

---

README.md
env.sample

Add documentation for getting an API key

---

src/components/DownloadsAndDocs.js

fixes: https://github.com/18F/crime-data-explorer/issues/209

remove localhost from link

---

src/components/ExplorerIntroNational.js

fixes: https://github.com/18F/crime-data-frontend/issues/860

bold dynamic usa overview content

---

src/components/NibrsCard.js
src/containers/AgencyChartContainer.js
src/containers/TrendContainer.js

fixes https://github.com/18F/crime-data-frontend/issues/1036

consistentfy dashes

---

src/components/NibrsTableWithBars.js

fixes: https://github.com/18F/crime-data-frontend/issues/821

fix nibrs table sort

---

src/components/ErrorCard.js

fixes: https://github.com/18F/crime-data-explorer/issues/192

better error message design/content

---

public/sw.js
sass/components/_glossary.scss
src/components/TrendChart.js
src/components/TrendChartDetails.js
src/components/TrendChartHover.js
src/components/TrendChartLineSeries.js
src/containers/TrendContainer.js
src/util/summary.js
test/components/TrendChart.test.js
test/components/TrendChartLineSeries.test.js
test/util/summary.test.js

Show data for both rape definitions as trend lines

---

src/components/About.js
src/components/DownloadsAndDocs.js
src/components/Home.js
src/components/Term.js

fixes: https://github.com/18F/crime-data-frontend/issues/1019

simplify type, fix wonky spacings

---

src/components/PlaceThumbnail.js

fixes: https://github.com/18F/crime-data-explorer/issues/171
preview:

show dc map when dc selected

---

sass/components/_viz.scss
src/components/AgencyChart.js

fixes: https://github.com/18F/crime-data-frontend/issues/986
preview:

responsively sized no data markers

---

src/components/NibrsHistogramDetails.js
src/components/NibrsTableWithBars.js
src/util/nibrs.js

fixes: https://github.com/18F/crime-data-frontend/issues/1010

iterate on nibrs chart copy

---

src/containers/NibrsContainer.js

fixes: https://github.com/18F/crime-data-frontend/issues/1029
preview:

nibrs heading iterate

---

src/components/AgencySearchResults.js

back to state stickiness

---

src/components/TrendChart.js
src/components/TrendChartLineSeries.js

per discussion with amber
preview:

remove trend series labels

---

src/components/About.js

Adds href styles

---

src/components/Home.js

Updating copy for Ryan

---

src/components/AgencyChart.js
src/components/AgencyChartDetails.js

fixes: https://github.com/18F/crime-data-frontend/issues/1065
preview:
cc: @RyanSibley @amberwreed

updated agency bar chart dynamic desc

---

src/components/About.js

about page tweaks

---

src/components/BetaBanner.js

Use shorter and more concise beta banner text

---

content/crimes/aggravated-assault.yml
content/crimes/arson.yml
content/crimes/burglary.yml
content/crimes/homicide.yml
content/crimes/larceny.yml
content/crimes/motor-vehicle-theft.yml
content/crimes/property-crime.yml
content/crimes/rape.yml
content/crimes/robbery.yml
content/crimes/violent-crime.yml

These should be sentences in a paragraph and not bullet points

fixing-data-considerations

---

src/components/NibrsIntro.js
src/containers/NibrsContainer.js

add nibrs agency ct

---

content/terms.json

Changing stuatory to statutory

glossary typo

---

content/crimes/violent-crime.yml

Removing glossary links from portions of `about violent crime data`

removing links

---

sass/components/_feedback.scss
src/components/Feedback.js

Update feedback text

---

src/components/Footer.js

Refs 18F/crime-data-explorer/issues/228

Remove phone # from footer

---

src/containers/AgencyChartContainer.js

I used class= instead of className= the first time.

fixing className

---

README.md

Update deployment URLs in README

---

package.json
src/server.js

Remove HTTP basic authentication

---

src/components/About.js
src/components/UcrResourcesList.js

Refs https://github.com/18F/crime-data-explorer/issues/207

Change h3 to h2 for doc outline

---

src/containers/TrendContainer.js

fixes: https://github.com/18F/crime-data-explorer/issues/229

fix rape trend download data

---

content/terms.json

CJIS submitted edits that are implemented here. See
https://github.com/18F/crime-data-explorer/issues/238

implemented glossary changes

---

src/components/Explorer.js

fixes: https://github.com/18F/crime-data-frontend/issues/1035
(will post comment tomorrow describing what was happening and why this fixes it)

header / explorer bug fix

---

src/components/NibrsHistogram.js

fixes: https://github.com/18F/crime-data-frontend/issues/1124

removes hover reset

---

public/sw.js

Uses ideas from https://serviceworke.rs/immediate-claim.html to make service workers active faster to try and prevent cache bugs
Refs https://github.com/18F/crime-data-explorer/issues/240

Use newest service worker to control the page

---

circle.yml

Try deploying to the staging environment with tags. Once this is confirmed to work, I will adjust so that it uses the production settings. Going to be merging a few PRs on my own since I think the `circle.yml` has to be on `master`/the default branch for circle to care about tags

Deploy on tags

---

circle.yml

Update autopilot cf plugin

---

src/components/TrendChart.js
src/components/TrendChartRapeAnnotate.js
src/components/TrendChartRapeLegend.js
test/components/All.test.js

Add revised rape legend

---

sass/components/_feedback.scss
src/components/Feedback.js

fixes: https://github.com/18F/crime-data-frontend/issues/988
preview:

feedback tweaks

---

content/locations.yml
sass/_variables.scss
src/components/DownloadsAndDocs.js
src/containers/ExplorerHeaderContainer.js

`/explorer/agency/AR0600900/violent-crime`
Closes #1135

Left align location label in explorer view

---

public/swagger/index.html

Change `signup for` to `sign up for`

---

public/robots.txt

Closes https://github.com/18F/crime-data-explorer/issues/257

Remove crawler restrictions from robots.txt

---

sass/_variables.scss
sass/components/_btn.scss
sass/components/_feedback.scss

To close https://github.com/18F/crime-data-explorer/issues/205

Show focus outline on button elements

---

src/components/Analytics.js

Fix DAP code snippet

---

content/datasets.yml
src/components/DownloadsAndDocs.js

adding arrest data and SHR data descriptions

---

src/components/NibrsIntro.js

Accidentally forgot this from #1179

Change "incidents" to "offenses" for state level views

---

package.json
src/containers/Home.js
src/containers/TrendContainer.js
src/routes.js
test/containers/TrendContainer.test.js
test/mocks/fileMock.js

Closes https://github.com/18F/crime-data-explorer/issues/261

Only show two trend lines

---

sass/util/_scroll.scss
sass/util/all.scss
src/containers/App.js

Prevent scrolling underneath sidebar on mobile

---

src/components/Feedback.js
test/components/Feedback.test.js

Also, clear the component's state after a successful submission so the
UI is empty.
Closes https://github.com/18F/crime-data-explorer/issues/267

Prevent user from submitting empty feedback

---

src/components/AgencySearch.js
test/components/AgencySearch.test.js

Show agency name in search box on refresh

---

content/datasets.yml

Fixes https://github.com/18F/crime-data-explorer/issues/273

Remove supplemental homicide report download

---

src/components/Footer.js

Different responsive layout for footer links

---

sass/util/_layout.scss
sass/util/_opacity.scss
sass/util/all.scss
src/components/SkipContent.js

Closes https://github.com/18F/crime-data-explorer/issues/268

Position skip content link offscreen until focused

---

CHANGELOG.md
package.json

Release that includes #1208 to ship some fixes and the 2015 data update to production

Bump version to 2.15.0

---

src/util/filter.js

-- issue was due to filter validation on agency

Fix to Agency View being broken

---

src/components/explorer/ExplorerIntroNational.js

Iss 277 Fix to Report Text not showing up properly in Location Explorer View

Iss 277 Fix to Report Text Issue

---

src/components/Sparkline.js
src/components/agency/AgencyChart.js
src/components/agency/AgencyChartDetails.js
src/components/trend/TrendChart.js
src/containers/SparklineContainer.js
src/server.js

- Data model changed so I had to adjust them both to use the new object.
- Not sure where the new object came from tho.

Agency Chart and Sparkline not showing data

---

src/components/PlaceThumbnail.js
src/containers/TrendContainer.js

There is an error thrown when the place is the national view in the explorer. It is trying to find the ID of the "active" state but there isn't one so we should just use the view of the whole country.

Fix error thrown from place thumbnail render

---

env.sample
manifests/base.yml
src/server.js
src/util/feedback.js
test/util/feedback.test.js
test/util/github.test.js

Eventually, this should actually notify somebody/something

Scan feedback text for keywords

---

src/components/XAxis.js

Fix to Date Range on Agency Chart no longer congested when range is greater than 10

iss286 - Fix to Date Range Chart

---

src/pages/Explorer.js

Remove .setOpen usage from Explorer page

---

manifests/base.yml
manifests/master.yml
manifests/production.yml
manifests/staging.yml
newrelic.js

Change the cloud.gov services used by the front end application to make it easier to change in the future and to share some with the API

Change cloud gov services

---

src/components/agency/AgencyChart.js
src/util/years.js
test/components/AgencyChart.test.js
test/util/years.test.js

@jpwentz I am opening this pull request against yours because it is a somewhat significant change to your code and didn't just want to overwrite it on your branch.
The main gist of what I'm doing here is pulling logic out of the `render()` method and encapsulating it into smaller class methods so that the logic can be more easily tested. I tried to simplify the component as well by removing duplicate internal state variables.
Let me know what you think, I'll hold off on merging #1219 until then.

Some changes to 1219

---

src/components/agency/AgencyChartDetails.js

per feedback from business line.

Fix to Fix Agency Narritive to display Actual and fix verbage

---

src/App.js
src/components/BetaBanner.js

NIBRS counts are off - along with the majority of the CDE data once the data was verified against publications and ucr data.

Add Banner back to CDE Frontend due to issues with CDE reporting inaccurate data

---

src/components/explorer/ExplorerIntroState.js

Use particpating_agencies for state Explorer intro

---

public/data/ucr-program-participation.json

Should close https://github.com/18F/crime-data-explorer/issues/337

Update some states NIBRS date ranges for downloads

---

src/pages/DownloadsAndDocs.js

Remove data dictionary link and point to different NIBRS data diagram

Change downloads & docs resource links

---

src/pages/Home.js

Simple Fix, and found this bug annoying.

Fix to Enable Home View Results Button
