src/components/Explorer.js, src/components/Glossary.js, src/components/Term.js, src/reducers/glossaryReducer.js, test/reducers/glossaryReducer.test.js
* Add state reducer for the SHOW_TERM action type
* `<Glossary />` uses the newly reduced state to show a term
I think this refs #78
=> Show glossary term properly

sass/components/_charts.scss, src/components/Explorer.js, src/components/TimeChart.js, src/components/YAxis.js
this PR does a couple things:
1) makes timechart responsive
2) adds a better tooltip: it finds the closest x coordinate that has a data point and then adds a vertical line and a text box with the data values for all points along that vertical y line intersection
i.e.,
=> responsive timechart, better tooltip

src/util/http.js, src/util/localStorage.js, test/util/localStorage.test.js
Since the data can be heavily cached, we can use localStorage to cache all the responses to improve the functioning of the application. We use the API URL as a cache key (with all query params sorted alphabetically for consistency), and store the serialized JSON response from the API.
If localStorage is not available, the app will just make the request everytime it is needed.
Closes #96
=> Store all API responses in localStorage to increase speed

src/components/Home.js, src/components/LocationFilter.js, src/components/LocationSelect.js
Use the homepage selects to trigger app state updates since they are effectively filters. Then use that reduced app state to determine what to show in the UI. This is definitely a quick pass, and the button doesn't yet also update the URL
=> Trigger filter update actions from homepage

src/components/NibrsTable.js
2 things: 1) added 'download data' buttons to each nibrs table 2) updated the format of numbers in the table so that they are more uniform in length (vs. being between 1-7 digits long), i.e.,
=> nibrs data download

sass/util/_border.scss, sass/util/_display.scss, sass/util/_space-addon.scss, sass/util/all.scss, src/components/Footer.js
Alter the way `<Footer />` renders to DRY out the code and to have responsive styling.
Should close [crime-data-api#325](/18F/crime-data-api/issues/325)
=> Make footer stylings responsive

src/components/NibrsTable.js, test/components/NibrsTable.test.js
all entries after "rowLim" are collapsed into an "Other" bucket; tests included!
preview:
=> collapse nibrs entries into "other"

src/components/UcrParticipationInformation.js
Links will be undefined for the national view right now, so it should
be an empty array so that the rendering can still occur
#299
=> Fix bug that enables national view to render with crime trends

src/components/TrendContainer.js
Current implementation:
@AvivaOskow and @amberwreed In the design, "Summary (SRS)" is underlined as if it is a link. What should that do? I was thinking it might be a term but it didn't have the glossary icon next to it.
@nicoleslaw Ping for your approval too
To close #254
=> Add source to trend chart

src/components/DownloadBulkNibrs.js, src/components/Home.js, src/components/NibrsTable.js, src/components/UcrParticipationInformation.js
this fixes https://github.com/18F/crime-data-explorer/issues/288 and makes the other dataset boxes on homepage have a uniform background height (regardless of content length):
=> design tweaks

src/components/Histogram.js
I think that this should fix a bug where the Histogram details component causes the explorer view to crash while rendering. If there is no data, then the histogram will just be blank and the histogram details component will not be used.
=> Fix histogram details error when there is no data

src/util/offenses.js
Uses the new `explorer_offense` parameter so that the UI -> official crime mapping can be done by the API. With this change, all of the trend charts should work for all crime types.
I will note that the NIBRS dimensions do not change to reflect "All violent crime" or "All property crime". I'll have to check through the issues to see what the expected behavior is
The API mapping can be found here:
https://github.com/18F/crime-data-api/blob/master/crime_data/common/base
.py#L507
=> Use explorer_offense for consistent mapping of summary offenses

data/ucr-program-participation.json, src/components/DownloadBulkNibrs.js, src/components/NibrsContainer.js, test/util/ucr.test.js
Update the types of data that each state submits to the UCR program. Having a `true` value for a type of data means that the state DOES submit that data. Therefore, the "hybrid" key has been converted into a derived state when both `srs` and `nibrs` are submitted.
@brendansudol I think this will be useful for creating the participation map on the About page
=> Update UCR program participation data

content/datasets.yml
I updated the URLs for the datasets based on [this comment in 237](https://github.com/18F/crime-data-explorer/issues/237#issuecomment-282077346), but this shouldn't be merged until the files are put on S3.
=> Update other dataset links

src/components/TrendContainer.js
I poorly resolved a merge conflict and ended up crashing the app since it was trying to use the <Term /> component in a container where it was not defined.
=> HOTFIX: Remove old term code from <TrendContainer />

src/components/Disclaimer.js
Fixes https://github.com/18F/crime-data-api/issues/378
=> Show beta banner on all devices/displays

sass/components/_viz.scss, src/components/TrendChart.js
=> Add legacy rape definition change indicator for 2013

src/components/NibrsDonut.js, src/components/NibrsDonutDetails.js
=> Apply hover effect when hovering on donut arc or detail line

src/components/DownloadDataBtn.js, src/components/NibrsCard.js, src/components/NibrsContainer.js, src/components/NibrsTable.js
The download button should give the user data from the entire card, not
just the last table component. I moved the data download button out and
into the NibrsCard, passing in the crime and place name so the
downloaded file has a useful name.
Right now the data download button only returns the first item in the
data array, but it should actually trigger multiple downloads if there
are multiple datasets inside of the nibrs card.
Noticed that the nibrs demographic data download is only one out of the three expected CSVs so I opened #538 for that.
Refs #501
=> Change data download names

sass/util/_height.scss, sass/util/all.scss, src/components/NibrsHistogramDetails.js
=> Set minimum height for NIBRS histogram details

package.json
Get rid of error in `master` deploy environment that says react isn't minified for production.
=> Build JS for production

src/actions/filters.js, test/actions/filters.test.js
Before updating filters, check to make sure the `crime` and `place` filters are valid. If they are not, remove them
=> Ensure that filters with bad place or crime values are ignored

src/util/ucr.js, test/util/ucr.test.js
Check to make sure `place` and `crime` are valid and known before using them to trigger some UCR-related API calls.
Now that we have SSR and `window.__STATE__` is generated on the server, we should be more careful about using values right from the URL without checking them first. At the very least, this results in lots of errors from API calls that aren't valid.
=> Check values before triggering API fetches

src/components/Glossary.js
Ensuring that the term is always lower cased fixed part of #599
Instead of crashing the application, show the user an error that informs them that their term cannot be found.
=> Show missing term error in <Glossary />

src/actions/composite.js
Now that we fetch the national participation data from the API, we cannot assume it will just be there when we need to draw trend lines. Right now this is causing the explorer interface to crash.
Because `shouldFetchUcr()` will return true for the `nationalKey` when it is the place and we don't want to fire off two requests for the same data, `fetchNational` will be false when the place is national.
=> Fetch national participation data

package.json
The Cloud Foundry buildpack got updated and node `v6.9.x` was removed in favor of `v.6.10.x` on the LTS branch.
Update the `package.json` so deploys to cloud.gov do not fail
=> Update node LTS version

src/components/NibrsContainer.js
Should address this [point from Nicole](https://github.com/18F/crime-data-explorer/issues/599#issuecomment-287437840) about backdated text including a glossary term link.
=> Make NIBRS text a <Term />

src/components/NibrsTable.js
@amberwreed Defaulting to percents still has a sentence with the total counts that don't add up.
Default to counts:
Default to percents:
Refs #631
=> Show percents by default in <NibrsTable />

README.md, manifests/demo.yml, manifests/master.yml, manifests/staging.yml, src/server.js
Document release process to facilitate sharing with the FBI and set the app to use a `CDE_API` environment variable for the API host URL instead of having it in the code base. This makes it easier to switch to using the more stable `-demo` API when we deploy a tagged release.
=> Document release process

package.json, src/server.js, webpack.client.config.js
To reduce the size of the file we transfer over the network, we want to gzip, at least, the `bundle.js` file.
Using some middleware that checks for a compressed file (by adding `.gz` to the requested file name) and serves it if available. Otherwise, serves the static files just like before.
size of `bundle.js`:
|  | development | production
--|--|--
without gzipping | 2.3MB | 799KB
with gzipping | 522KB | 249KB
=> Gzip bundle.js in build process

src/components/Footer.js, src/server.js
Quick proposal for #594, adding version number to `/status` response and to the `<Footer />` component
=> Add app version to /status and to footer

package.json, src/components/DownloadDataBtn.js, src/components/NibrsCard.js
The browser alert/permission request to download multiple files is subtle on many popular browsers so it was confusing people as to why their files didn't download. Instead, we can wrap all the files into a single .zip file so that the user can easily get all the relevant data.
=> Zip CSV file downloads so there is only one file

src/util/history.js, test/util/history.test.js
this fixes a bug where the state param was getting dropped if the user updated the time filter in the sidebar
=> fixes time filter / url bug

sass/util/_border.scss, src/components/NibrsContainer.js, src/components/NoData.js, src/components/TrendChart.js, src/components/TrendChartDetails.js, src/components/TrendContainer.js
* better rate comparison robotext (https://cl.ly/k2za)
* not showing decimals for larger numbers (+ added footnote about rounding)
* updated chart title box design (white background, navy border bar)  
Closes 18F/crime-data-explorer#33
=> chart refinements

src/components/TrendContainer.js
We should have two lines on the trend chart for rape (per place), one
for the revised definition and one for the legacy definition
=> Show "rape_legacy" data when the crime is "rape" for now

package.json, src/entry.js, src/html.js, src/util/analytics.js, webpack.client.config.js, webpack.server.config.js
Add [`autotrack`](https://github.com/googleanalytics/autotrack) so that URL changes in the single page app are still tracked in Google Analytics. It would be good to implement the following other autotrack plugins, but they shouldn't necessarily hold up merging:
- [`impressionTracker`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/impression-tracker.md)
- [`maxScrollTracker`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/max-scroll-tracker.md)
- [`mediaQueryTracker`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/media-query-tracker.md)
- [`pageVisibilityTracker`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/page-visibility-tracker.md)
Closes 18F/crime-data-explorer#72
=> Add more Google analytics tracking

src/components/NibrsContainer.js
Fix an issue where NIBRS incidents counts (in the initial NIBRS paragraph) can be significantly higher than the other numbers in the interface. For example, using rape offenses in Alabama (`/explorer/state/alabama/rape`) it showed that there were over 3K incidents for the time period between 2004 and 2014. In fact, we weren't respecting the `since` or `until` dates and the numbers for the early 1990s in Alabama are really high. Now the number in the paragraph is much closer to the other numbers in the NIBRS cards.
API response:
```
{
"count": 661,
"year": "1991",
"offense_name": "rape",
"race_code": "B"
},
{
"count": 659,
"year": "1991",
"offense_name": "rape",
"race_code": "U"
},
{
"count": 296,
"year": "1991",
"offense_name": "rape",
"race_code": "W"
}
```
Before:
After:
=> Use data filtered by year before making total NIBRS incident count

src/components/AboutTheData.js
Because these event listeners are attached to the document, we have to be careful about only preventing defaults when the event matches the requisite elements. This manifested as the sidebar crime filters not responding to click events
=> Do not prevent all defaults on click events from <AboutTheData />

src/util/summary.js, test/util/summary.test.js
Fix problem where trend line was doubling back on itself.
Before:
After:
=> Sort summary data by date

sass/components/_forms.scss, sass/components/_viz.scss, sass/util/_space-addon.scss, src/components/NibrsContainer.js, src/components/NibrsHistogram.js, src/components/TimePeriodFilter.js, src/components/TrendChart.js, src/components/TrendChartDetails.js, src/components/TrendContainer.js, src/components/XAxis.js, src/components/YAxis.js, src/util/years.js
cc: https://github.com/18F/crime-data-explorer/issues/44
this should have everything (sans the dropdown); i also would like to refactor the trend details table soon now that it's getting more complex. (as another issue)
preview:
=> refine trend chart

src/components/TrendChartDetails.js, src/util/api.js, test/util/api.test.js
Fetch arson data from the API (which is not estimated) and display in the trend chart using the population from the estimates endpoint.
Should close https://github.com/18F/crime-data-explorer/issues/110
=> Display arson data

src/components/TrendChart.js, src/components/TrendChartDetails.js
i tried to left align the label text above/below the last point (per mockup) but the text didn't fit within the SVG bounding box, hence this centered-aligned approach
the label is always above the line that is bigger (as of the last year) and below the line that is smaller (per mockup)
preview:
cc: @AvivaOskow @amberwreed 
closes https://github.com/18F/crime-data-frontend/issues/281
=> add labels to trend chart

src/components/About.js, src/components/DownloadBulkNibrs.js, src/components/DownloadsAndDocs.js, src/components/Home.js, src/components/NibrsContainer.js, src/components/Term.js, src/components/TrendChartDetails.js, src/components/TrendSourceText.js, src/components/UcrParticipationInformation.js
Sometimes we were passing dispatch through a few layers just to get to
a <Term /> component. Instead, the component can be connected to the
redux store so that it is always passed a copy of the store's dispatch
function.
=> Connect <Term /> so dispatch isn't required as a prop

src/components/AgencyChartContainer.js, src/components/Explorer.js, src/components/NibrsContainer.js, src/components/SidebarContainer.js, src/components/TrendContainer.js, src/components/UcrParticipationContainer.js
Using the `connect()` helper to simplify what is required inside of <Explorer /> and establishes a pattern for components that get a lot of data out of the application state.
Right now, all the container components are in the same directory as the rest of the more presentational components but they're all connected to get props directly from the store.
=> Connect *Container components to redux

.gitignore, package.json, public/swagger/crime-data-style.css, public/swagger/index.html, public/swagger/swagger.json, src/components/DownloadsAndDocs.js, src/components/Home.js, src/server.js, src/util/api.js, test/util/api.test.js
@brendansudol I think this is ready for your review.
I didn't want to check in the Swagger files since that always seems to be more hassle than its worth if we ever wanted to upgrade. I made added `swagger` as an npm script and included it in `postinstall` so that it will run after the packages are all installed but not on every build. If you pull this down and run `npm install` to install swagger, the "build" task for swagger should run as well.
Right now the swagger route is `/docs`. Since there are a bunch of different things that could be documentation on this project, I think it would be nice if the route was `/api`. However, we currently use that route for our API proxy. I imagine a few potential solutions, which I listed in order of my preference:
1. Moving the proxy route to …
=> Style swagger documentation

data/terms.json
I’ve added revised and legacy rape definitions back to the glossary
with the same definition as `rape`.  I hope this fixes the “not found”
error.
=> adding revised and legacy back to glossary -- might address issue #121

package.json, src/components/DownloadBulkNibrs.js, src/components/DownloadDataBtn.js, src/util/analytics.js
The outboundLinkTracker plugin for Google analytics seems to be causing
a bug with downloading files in IE.
Closes https://github.com/18F/crime-data-explorer/issues/131 by removing that tracker.
=> Fix IE downloads

src/components/NibrsContainer.js
Crimes that have NIBRS dimensions were failing to load for the national
perspective. The reason is because we abstracted away the default place
and placeType values into the place util but didn't use in the NIBRS
container
=> Map default place related filters to NibrsContainer

src/components/SparklineContainer.js
We have two different definitions of rape, so I'm using "rape_legacy" here to draw the sparklines. This begs another question @AvivaOskow and @LarryBafundo: what should the sparklines look like for rape given the fact that we have two definitions?
Closes https://github.com/18F/crime-data-explorer/issues/168
=> Fix sparklines for rape views

src/components/AgencyChartContainer.js, src/components/Loading.js, src/components/NoData.js, src/components/SparklineContainer.js
=> No data text change for agency view

src/components/ExplorerUsStateIntroduction.js
I don’t know if this will work, but I added a space after
{startCase(place)}.
https://github.com/18F/crime-data-frontend/issues/842
Sorry for the misleading branch name. I planned to do something else
when I set out.
=> trying to fix the space issue in state overview text

sass/components/_viz.scss, src/components/AgencyChart.js
=> Add indicator for years with 0 values

src/components/AgencyChart.js
(needs to be 3, not 4, so gridlines are on whole numbers)
refs: https://github.com/18F/crime-data-explorer/issues/166
preview:
=> set higher yaxis min for agency chart

circle.yml, scripts/deployAndDelete.js
A pain point in our workflow is getting design approval to changes. It would be awesome to have automatic apps and unique URLs created for each pull request so that we can do code reviews and design reviews without merging and closing the original issue.
This is a first attempt at doing something like that. It checks the latest commit for the pattern used by Github when pull requests are merged through the web interface, and if it is found it tries to delete the app created for that branch. If the branch isn't `master` and the last commit message doesn't have the merge pattern, then create a manifest file for the app and use it to deploy the app. It names the app `crime-data-explorer-${branch}` and binds a similar URL to the app like `https://crime-data-explorer-${branch}.fr.cloud.gov`. …
=> Deploy all branches to unique apps

manifests/master.yml, manifests/staging.yml
With our autodeploy feature we want to make apps as small as possible so that more than a few can be deployed. Since master and staging get very little traffic, I think its fine to shrink them down to the same size as the automatically created apps.
=> Shrink footprint of staging and master apps

manifests/base.yml, manifests/demo.yml, manifests/master.yml, manifests/staging.yml, src/server.js, src/util/env.js
Create a few new services in cloud.gov to store the different credentials and bind them through the manifests. Also adds a `env` util that combines all user provided services and `process.env` so that environment variables are easier to work with across local and deployed environments
Closes https://github.com/18F/crime-data-frontend/issues/401
=> Use API data gov proxy for -demo app

src/components/ExplorerIntroNational.js, src/components/ExplorerIntroState.js, src/components/Terms.js
=> Add estimated Term to state and national overview text

src/util/api.js, src/util/nibrs.js, test/fixtures/nibrsApiResponse.json, test/util/api.test.js
Closes https://github.com/18F/crime-data-explorer/issues/2
The offenders API is returning `null` counts, so the chart looks weird but I opened https://github.com/18F/crime-data-api/issues/562 for that.
=> Include offender and victim ethnicity in NIBRS charts

sass/components/_glossary.scss, src/util/md.js
=> Add glossary icons next to relevant links in About the Data

src/components/AgencyChartDetails.js, src/containers/NibrsContainer.js
Also, properly format crime name in agency chart details to remove the hyphen from multi-word offenses.
Refs https://github.com/18F/crime-data-explorer/issues/185
=> Show agency name instead of ORI in NIBRS container introduction text

src/components/NibrsTableWithBars.js
refs: https://github.com/18F/crime-data-explorer/issues/74
now only rounds for huge numbers (over 10k), for space considerations
preview:
=> fix improper rounding

src/components/AgencySearchResults.js, src/components/ExplorerIntroNational.js, src/components/ExplorerIntroState.js, src/components/NibrsStackedBarDetails.js, src/containers/ExplorerHeaderContainer.js, src/containers/NibrsContainer.js
Refs 18F/crime-data-explorer/issues/175
=> Use "No assigned county" instead of "Unspecified" in agency search results

sass/util/_colors.scss, src/components/About.js
* Change red color of legend and MS to #702C27
* Change the "U.S. territories are not included in the map" to say
"Other outlying areas include America Samoa, Guam, Puerto Rico, and
U.S. Virgin Islands."
Refs #989 https://github.com/18F/crime-data-explorer/issues/36
=> Update About page participation map

src/components/AgencyChart.js, src/components/AgencyChartDetails.js, src/containers/AgencyChartContainer.js
Use "offenses" as a unit if the agency submits SRS data and "incidents" if it submits NIBRS data.
URLs/ORIs for reviewing:
* `/explorer/agency/NJ0110500/homicide` - SRS agency with no data during reporting period
* `/explorer/agency/CA0210400/violent-crime` - SRS agency with data during reporting period
* `/explorer/agency/AR0020100/violent-crime` - NIBRS agency with data during reporting period
Refs #949
=> Update agency chart text to use proper unit

sass/_variables.scss, sass/components/_viz.scss, src/components/AgencyChart.js, src/components/ExplorerIntroState.js
hides every other bar chart axis label on small screens
preview:
fixes:
https://github.com/18F/crime-data-explorer/issues/203
=> fix mobile chart axis labels

src/components/ExplorerIntro.js, src/components/ExplorerIntroAgency.js
Refs https://github.com/18F/crime-data-frontend/issues/949#issuecomment-310523199
=> Update agency intro text

src/components/AgencySearch.js, src/components/AgencySearchResults.js
=> Add US state button to bottom of agency search results

sass/core/_color-base.scss, src/components/ExplorerIntroAgency.js, src/components/ExplorerIntroNational.js, src/components/Term.js
Refs https://github.com/18F/crime-data-frontend/issues/1031
also makes crime term glossary icon sizes consistent and improves underline display using `text-decoration-skip=ink` to match sketch designs
=> small content fixes

src/components/NibrsCard.js, src/components/NibrsCountPercentToggle.js, src/components/NibrsHistogram.js, src/components/NibrsTableWithBars.js
* moves count/percent toggle above tables (right aligned with title)
* updates font sizes
preview:
=> nibrs card tweaks

src/components/BetaBanner.js
New text:
> Please note that this site is still under development and will be updated on a periodic basis. Feedback is welcome so that we can provide a better service.
=> Change beta banner text

src/containers/NibrsContainer.js
The NIBRS section for an agency had a loading bug where it would appear to load for a while. This was caused by the fact that we were using both the NIBRS data and UCR data (from their respective reducers) to determine if we should show the loading screen or not. In addition, we set both loading to true for the server side render.
This works fine for state views that do actually make UCR requests and, therefore, set the loading flag to false for that reducer. If the user then looks at an agency, that would also work fine since the flag remains flipped. However, for an agency, we do not submit any UCR data related requests to the API and so the flag would never flip. This would result in the NIBRS data being available to show but not being shown because the app continues to show the …
=> Fix NIBRS loading error on agencies

sass/core/_base-tables.scss, sass/util/_width.scss, src/components/TrendChartDetails.js
fixes: https://github.com/18F/crime-data-frontend/issues/980
preview:
=> trend table overflow fix

src/components/NibrsHistogram.js
fixes: https://github.com/18F/crime-data-frontend/issues/524
preview (can't see mouse but i'm hovering over whitespace above the tiny bars):
=> bigger histogram tap targets

src/components/PlaceThumbnail.js
there was a bug where we assumed coordinates was an object with lat, lng when sometimes it wouldn't for agencies (see https://crime-data-explorer.fr.cloud.gov/explorer/agency/OR0031300/violent-crime)
=> lat, lng bug fix

src/containers/NibrsContainer.js, src/util/api.js, src/util/nibrs.js, test/fixtures/nibrsApiResponse.json, test/util/api.test.js, test/util/nibrs.test.js
Fixes https://github.com/18F/crime-data-explorer/issues/259
Use the `offense_name` variable for the offense endpoints to get a count. Recreate [the mapping from the API](https://github.com/18F/crime-data-api/blob/master/crime_data/common/base.py#L493-L506) to account for `explorer_offense` not working on that endpoint
=> Use offense endpoint to calculate NIBRS total

src/components/ExplorerIntroAgency.js, src/components/NibrsIntro.js
We are technically counting the number of reported offenses, not the
number of incidents which has a specific meaning in NIBRS. Incidents
can have many offenses associated with them, and most closely
correlates with a row of data. However, when regular folks are reading
this, the distinction is lost. So we'll use "offenses" since it is
technically more correct and has a very similar meaning to folks not
familiar with the NIBRS definition.
=> Change "incidents" to "offenses" in NIBRS

src/components/NibrsCard.js, src/components/NibrsStackedBar.js, src/components/NibrsStackedBarDetails.js, src/util/nibrs.js
Closes https://github.com/18F/crime-data-explorer/issues/198
=> Add percent/count toggle to stack bar chart, other small design changes

src/components/About.js, src/components/ExplorerIntro.js, src/components/ExplorerIntroAgency.js, src/components/ExplorerIntroState.js, src/components/LocationFilter.js, src/components/LocationSelect.js, src/components/PlaceThumbnail.js, src/components/TrendChartDetails.js, src/components/TrendSourceText.js, src/components/UcrResourcesList.js, src/components/UsaMap.js, src/containers/ExplorerHeaderContainer.js, src/containers/Home.js, src/containers/SparklineContainer.js, src/containers/TrendContainer.js, src/util/agencies.js, src/util/api.js, src/util/participation.js, src/util/usa.js, test/components/LocationFilter.test.js, test/util/api.test.js, test/util/usa.test.js
Also change the way that display names are generated for states (and DC) so that they are consistent across the application and come from the USA utility. This change touches a lot of files, but hopefully simplifies things in the long run since it makes display names predictable and reduces the need to remember to use text formatting functions throughout components.
Closes #1008 
cc @svacovsky and @bdstout1617
=> Use "Washington, DC" instead of "District of Columbia"

package.json, sass/components/_tables.scss, src/components/About.js
Adds a tabular representation of the UCR participation data for a11y (fixes #1173) and mobile users. Needs to be merged after #1184
=> Add table representation of UCR participation to About page

src/App.js, src/pages/About.js, src/pages/DownloadsAndDocs.js, src/pages/Explorer.js, src/pages/Home.js, src/pages/NotFound.js
Use the pattern from `<App />` to bind action creators to dispatch (so that we don't need to pass dispatch into the props of a component) in the page level components (`/src/pages`) for consistency.
Also remove `appState` so that the page level components can use `connect()` to pull the relevant parts of the application state for themselves.
=> Bind action creators to dispatch for page level components and remove appState

src/actions/summary.js, src/util/agencies.js, src/util/summary.js, test/util/participation.test.js
Refactor to use a common library instead of duplicated code and add tests to another another similar function in participation util
=> Agency & summary utils & summary actions use reduce-entries

src/actions/summary.js, src/util/summary.js, test/actions/summary.test.js, test/util/summary.test.js
Note that this PR isn't not against master, but `jk-jw-all-composite-charts` which is another in-progress feature branch.
The `mungeSummary` data function was doing quite a bit all in one call which made it require a lot of parameters and was harder to follow. It has been refactored into a series of smaller helper functions that are used at different points in the app. This way the data is reduced into a more usable form that requires no further calculation, just shape manipulation and filtering.
Added tests for all new functions in summary util
=> Refactor mungeSummaryData util function

README.md, src/containers/TrendContainer.js
The big charts in these views are for the all violent/property crime trend chart, but it is included in the offense utility. Manually mapping the component offenses for now
Current `master`:
Changed:
=> Remove small charts for violent crime or property crime

CHANGELOG.md, src/server.js
Minor cleanup of the formatting for release notes to keep them consistent with the previous format. I like to hide the URLs with small links to reduce the visual clutter in the document.
=> Cleanup feedback endpoint and release notes

src/components/nibrs/NibrsIntro.js, src/containers/NibrsContainer.js
We were just using the participation data from the until year, and not the whole range for the NIBRS container. This resulted in a weird thing where DC would show up as having 1 homicide reported by 0 agencies because there was no data in 2015.
=> Show accurate agency count for NIBRS participation

sass/components/_glossary.scss, sass/components/_layout.scss, src/containers/SidebarContainer.js
Animate the opening and closing of the sidebar to match the opening and closing of the glossary component on mobile devices.
=> Animate sidebar opening and closing

manifests/production.yml, newrelic.js, src/server.js
Update a few things to make the new relic integration better:
1. Use the proper cloud.gov user-provided service to get the API key
2. Put the conditional in the config file
3. Update production to have 2 instances to avoid noisy downtime alerting
=> Change how new relic is integrated

src/pages/Home.js
The prop that gets passed through is place, not usState. This was causing the state to be undefined and therefore to show the national view.
Fixes #1244
=> Handle home page state selection properly

manifests/base.yml
Broke production because we were accidentally sharing an
API key that the front end app was using but returning
403 errors.
Change the services so that there are fewer shared ones
between the API and the front end application.
=> Use a different service for the New Relic key

src/components/trend/TrendChart.js
Current Breakage if the Year Selected in Charts is outside the range of the next date search. IE I have 2006-2016 selected as Time Period. I then change the time period to 2005-2015 it will not load in the year selected on the previous page was 2016 the charts will not load. This is a critical fix.
=> Fix to Data Range Change Errors

public/data/ucr-program-participation.json
Nebraska is listed as incident data only – Nebraska has NIBRS and summary agencies reporting
Michigan is listed as NIBRS and Summary – Michigan is all NIBRS reporting
Minnesota is listed as Summary only – Minnesota is NIBRS certified and has at least one agency reporting NIBRS  in 2016
Georgia is listed as Incident and summary – Georgia is only summary reporting
Rhode Island is listed as Incident and Summary – Rhode Island is all NIBRS reporting
=> •	CDE Participation About Page reporting incorrect details whether State is Incident or NIBRS State

public/data/ucr-program-participation.json, src/components/DownloadBulkNibrs.js
To handle the fact that Colorado started submitting NIBRS data in 1992 but then stopped for 1995 and 1996 I added a no-data-years optional array to the UCR program participation data. These years are not included in the year drop down for bulk NIBRS downloads.
Closes https://github.com/18F/crime-data-explorer/issues/337
This doesn't really mess up any of our other views but does make the introduction text under "Incident details" less accurate. For example, Colorado did not submit incident details/NIBRS data for 1995 or 1996 but if the range 1995-2016 is selected then the sentence reads as follows:
Should we update that view to be more accurate? For example, we could say:
=> Adjust NIBRS bulk download menus

public/data/ucr-program-participation.json
Per the [updated comment on crime-data-explorer#337](https://github.com/18F/crime-data-explorer/issues/337#issuecomment-355460828), I updated the NIBRS download drop downs to reflect the gap years for Alabama and Illinois.
It does make me think that we should provide some explanation for why large, 10+ year gaps are missing for some states as it looks a bit like a UI error otherwise:
=> Reflect NIBRS gap years for Alabama and Illinois

package.json
The node version got bumped up in the buildpack we use, so [deploys are failing](https://circleci.com/gh/18F/crime-data-frontend/2564). This updates the app accordingly and should restore deploys once merged.
=> Update version of node to 6.12.x

src/util/api.js
Arson Totals were displaying the national counts twice. State Arson numbers === Nationa Arson numbers.
=> Fix to Arson not reporting
